mainapp/urls.py
from django.urls import path
from mainapp.views import main, shop, whoa, it, projects, good, add_to_cart, CategoryView, ProductView, CartView, GenreView, PoemView

app_name = "mainapp"


urlpatterns = [
    path("", main, name="main"),
    path("shop/", shop, name="shop"),
    path("mainpage/", whoa, name="mainpage"),
    path("it/", it, name="it"),
    path("projects/", projects, name="projects"),
    path("api/category/", CategoryView.as_view()),
    path("api/product/", ProductView.as_view()),
    path("api/cart/", CartView.as_view()),
    path("api/genre/", GenreView.as_view()),
    path("api/poem/", PoemView.as_view()),
    path("shop/good/<int:good_id>", good, name="good"),
    path("shop/add_to_cart/<int:good_id>", add_to_cart, name="add_to_cart")
]

novela/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("frontend_app.urls", "frontend")),
    path("old/", include("mainapp.urls", "mainapp")),
    path("user/", include("userapp.urls", "userapp")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userapp/urls.py
from django.urls import path, include
from userapp.views import login, user_main, registration

app_name = "userapp"

urlpatterns = [
    path("", user_main, name="user_main"),
    path("login/", login, name='login'),
    path("registration/", registration, name="registration"),
]

mainapp/models.py
from django.db import models
from uuid import uuid4
from userapp.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128,unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.id}. {self.name}'

class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2,max_digits=6)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to="product_images")
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.id}. {self.name}'
    
    @property # то действие стало, как переменная
    def category_info(self):
        categ = Category.objects.get(id = self.category_id)
        return categ
    
    
class Cart(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    device_id = models.UUIDField(default=uuid4)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

    

class Genre(models.Model):
    name = models.CharField(max_length=100,unique=True)

    def __str__(self):
        return f'{self.id}. {self.name}'


class Poem(models.Model):
    genre = models.ForeignKey(to=Genre, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=128)
    text = models.TextField()
    img = models.ImageField(upload_to="poem_images", null = True, blank=True)

    def __str__(self):
        return f'{self.id}. {self.name}'
    
    @property # то действие стало, как переменная
    def genre_info(self):
        genre = Genre.objects.get(id = self.genre_id)
        return genre
    

mainapp/views.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse, HttpResponseRedirect

from mainapp.models import Product,Category,Poem,Cart
from userapp.models import User
from userapp.forms import UserLoginForm
from rest_framework import generics
from .serializers import *
from uuid import uuid4


# Create your views here.
def main(request):
    try:
        device_id = request.session['device_id']
    except KeyError:
        request.session['device_id'] = str(uuid4())
    
    print(request.session['device_id'])
    # filter - он отдает список либо пустой либо с элементами
    # get - Отдает четко это элемент, если элементов не 1, то ошибка
    # print(list(Category.objects.all().values_list()))
    #Product.objects.create()
    return render(request, "thank_god.html")


def shop(request):
    try:
        device_id = request.session['device_id']
    except KeyError:
        request.session['device_id'] = str(uuid4())
    
    category = request.GET.get('category')
    if category == None:
        products = Product.objects.all()
    else:
        products = Product.objects.filter(category_id = category)
    categorys = Category.objects.all()
    context = {"products": products, 'categorys':categorys}
    return render(request, "shop.html", context)


def whoa(request):
    poems = Poem.objects.all()
    context = {'poems':poems}
    return render(request, "index.html",context)



def it(request):
    return render(request, "it.html")

def projects(request):
    # products = Product.objects.all()
    # return HttpResponse(products)
    return render(request, "projects.html")

def good(request, good_id):
    good_info = Product.objects.get(id = good_id)
    context = {"good_info": good_info}
    return render(request, "good.html", context)

def add_to_cart(request, good_id):
    try:
        device_id = request.session['device_id']
    except KeyError:
        request.session['device_id'] = str(uuid4())
        device_id = request.session['device_id']

    user_id = request.user.id
    if user_id==None:
        cart_obj = Cart.objects.filter(device_id=device_id, product_id=good_id, user_id=user_id)
    else:
        cart_obj = Cart.objects.filter(product_id=good_id, user_id=user_id)
    if cart_obj.exists():
        cart_obj = cart_obj.first() # cart_obj[0]
        cart_obj.quantity += 1
        cart_obj.save()
    else:
        cart = Cart.objects.create(device_id=device_id, product_id=good_id, user_id=user_id, quantity=1)
        cart.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

class CategoryView(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

class ProductView(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

class CartView(generics.ListAPIView):
    queryset = Cart.objects.all()
    serializer_class = CartSerializer

class GenreView(generics.ListAPIView):
    queryset = Genre.objects.all()
    serializer_class = GenreSerializer

class PoemView(generics.ListCreateAPIView):
    queryset = Poem.objects.all()
    serializer_class = PoemSerializer

    def get(self, request, *args, **kwargs):
        genre_id = request.GET.get('genre')
        if genre_id:
            self.queryset = self.queryset.filter(genre_id=genre_id)
        return super().get(request, *args, **kwargs)

    
'''
JSON - JavaScript Object notation
{'persons':[{'name':'Вова'},{'name':'Даша'},{'name':'Cаша'}]}

REST API - Representation state transfer

Клиент -> request ->       Сервер
       <- Json response ->

'''

mainapp/templates/good.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{good_info.name}}</title>
</head>
<body>
    
    <h1>{{good_info.name}}</h1>
    <img src="{{good_info.image.url}}" alt="" class="image">
    <p>{{good_info.price}}</p>
    <p>{{good_info.description}}</p>
    <a href="{% url 'add_to_cart' good_info.id%}">Купить</a>
</body>
</html>

mainapp/templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="ru">

<head>
    <link rel="stylesheet" href="{% static 'vendor/css/chich.css'%}">
</head>

<body>
    <div class="joy">
        <img class="flower" src="{% static 'vendor/img/flower.png' %}" alt="">
        <img class="flower2" src="{% static 'vendor/img/flower.png' %}" alt="">
        <img class="flower3" src="{% static 'vendor/img/flower3.png' %}" alt="">
        
        <img class="flower4" src="{% static 'vendor/img/flower4.png' %}" alt="">
        <img class="flower5" src="{% static 'vendor/img/flower5.png' %}" alt="">
        <img class="butterfly" src="{% static 'vendor/img/butterfly1.png' %}" alt="">
    </div>
    <div class="container">
        
        <div class="poems">
            {%for poem in poems%}
            <div class="poem" style="background: url('{{poem.img.url}}'); background-size: cover;">
                {{poem.text}}
            </div>
           
            {%endfor%}
        </div>
                
    </div>
    

</body>

</html>

mainapp/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'vendor/css/login.css' %}">
</head>

<body>

    <form action="{%url 'userapp:login'%}" method="POST">
        {% csrf_token %}
        <div class="input-field">
            <label for="{{form.username.id_for_label}}">Логин:</label>
            {{form.username}}
        </div>
        <div class="input-field">
            <label for="{{form.password.id_for_label}}">Пароль:</label>
            {{form.password}}
        </div>

        <input type="submit">
    </form>

</body>

</html>

mainapp/templates/reg.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'vendor/css/reg.css' %}">
</head>

<body>
    <form action="{%url 'userapp:registration'%}" method="POST">
        {% csrf_token %}
        <div class="input-field">
            <label for="{{form.first_name.id_for_label}}">Имя</label>
            {{form.first_name}}
            {{form.first_name.errors}}
        </div>
        <div class="input-field">
            <label for="{{form.password.id_for_label}}">Фамилия</label>
            {{form.last_name}}
            {{form.last_name.errors}}
        </div>
        <div class="input-field">
            <label for="{{form.email.id_for_label}}">Кличка</label>
            {{form.username}}
            {{form.username.errors}}
        </div>
        <div class="input-field">
            <label for="{{form.email.id_for_label}}">Эл.почта</label>
            {{form.email}}
            {{form.email.errors}}
        </div>
        <div class="input-field">
            <label for="{{form.password1.id_for_label}}">Придумайте пароль</label>
            {{form.password1}}
            {{form.password1.errors}}
        </div>
        <div class="input-field">
            <label for="{{form.password2.id_for_label}}">Повторите пароль</label>
            {{form.password2}}
            {{form.password2.errors}}
        </div>
        <input type="submit">
    </form>

</body>
</html>

mainapp/templates/shop.html
{%load static%}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'vendor/css/shop.css'%}"> 
</head>
<body>
    <div class="contsht">
        <div class="shtuka">
            <img src="{%static 'vendor/img/blending1687548579848.svg'%}" alt=''></img>  
        </div>
        <div class="sht2">
            <img src="{%static 'vendor/img/blending1687549622625.svg'%}" alt=""></img>
        </div>
    </div>

    <div class="menu">
        <div class="title"><h1><span>В</span>ыберите категорию товара:</h1></div>
        <div class="list-menu">
            <ul>
                <li><a href="/shop">Все</a></li>
                {%for category in categorys%}
                    <li><a href ='?category={{category.id}}'>{{category.name}}</a></li>
                {% endfor %}
                
            </ul>
        </div>
    </div>
    

    <div class="container">
        {% for product in products %}
        <a href="good/{{product.id}}">
            <div class="product">
                <h1>{{product.name}}</h1>
                <img src="{{product.image.url}}" alt="" class="image">
                <p>{{product.price}}</p>
            </div>
        </a>
        {% endfor %}
    </div>
    
    
    
</body>
</html>